---
- hosts: all
  tasks:
    - name: Display ansible_os_family
      ansible.builtin.debug:
        var: ansible_os_family

    - name: Display distribution
      ansible.builtin.debug:
        var: ansible_facts['distribution']

    - name: Display distribution_major_version
      ansible.builtin.debug:
        var: ansible_facts['distribution_major_version']

    - name: Display os_family
      ansible.builtin.debug:
        var: ansible_facts['os_family']

    - name: Display compiled host info
      ansible.builtin.debug:
        msg: >-
          Host {{ ansible_nodename }}
          based on {{ ansible_facts['os_family'] }}
          has {{ ansible_facts['distribution'] }}
          version {{ ansible_facts['distribution_major_version'] }} installed.
