---
# tasks file for roles/ansible

- name: Install required packages
  ansible.builtin.apt:
    name:
      - sudo
      - openssh-server
      - python3-apt
    state: present
  tags:
    - sudo
    - ssh


- name: Ansible user tasks
  tags: user
  block:
    - name: Group ansible
      ansible.builtin.group:
        name: ansible
        system: true
        state: present

    - name: Make sure ssh group is present
      ansible.builtin.group:
        name: ssh
        system: true
        state: present

    - name: User ansible
      ansible.builtin.user:
        name: ansible
        group: ansible
        groups: ssh,sudo
        home: "{{ ansible_common.home }}"
        shell: /bin/sh
        system: true
        state: present

    - name: Add ssh keys for Ansible user
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ item }}"
        state: present
      loop: "{{ ansible_common.ssh_keys }}"

    - name: Remove old ssh keys
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ item }}"
        state: absent
      loop: "{{ ansible_common.ssh_keys_removed }}"


- name: Prepare directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('ansible') }}"
    group: "{{ item.group | default('ansible') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - path: "{{ ansible_common.home }}"
      mode: '0750'

    - path: "{{ ansible_common.home }}/creates"

    - path: /opt/scripts
      owner: root
      group: root


- name: Ansible sudo configuration tasks
  tags: sudo
  block:
    - name: Configure sudo for ansible
      ansible.builtin.template:
        src: sudoers.j2
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: '0440'
        validate: /usr/sbin/visudo -cf %s

    - name: Disable old-style ansible sudo config
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: '^\s*ansible\b'
        validate: /usr/sbin/visudo -cf %s

    - name: Allow useful environment variables for sudo
      ansible.builtin.blockinfile:
        path: /etc/sudoers
        state: present
        marker: "# {mark} Ansible managed env variables"
        prepend_newline: true
        block: |
          Defaults env_keep += "SSH_*"
          Defaults env_keep += "EDITOR"
        validate: /usr/sbin/visudo -cf %s


# NOTE: Whitespace in regexp is intended to allow sections configuration (Match...)
- name: Configure sshd
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: "{{ item.state | default('present') }}"
    regexp: '^\s*{{ item.name }}\b'
    insertbefore: '^# BEGIN'
    firstmatch: true
    line: "{{ item.name + ' ' + item.value if item.value is defined else omit }}"
  notify: restart sshd
  loop:
    - name: 'AllowUsers'
      state: absent
    - name: 'AllowGroups'
      value: 'ssh'
    - name: 'PermitRootLogin'
      value: 'no'
    - name: 'MaxStartups'
      value: "{{ ansible_common.ssh_max_startups }}"
  tags: ssh
