---
# tasks file for roles/ansible

- name: Install required packages
  ansible.builtin.apt:
    name:
      - sudo
      - openssh-server
      - python3-apt
    state: present
  tags:
    - sudo
    - ssh


- name: Ansible user tasks
  tags: user
  block:
    - name: Group ansible
      ansible.builtin.group:
        name: ansible
        system: true
        state: present

    - name: Debug merge
      ansible.builtin.debug:
        var: ansible_common
