---
# tasks file for ansible
- name: Create user ansible
  ansible.builtin.user:
    name: ansible
    groups: sudo,ssh
    home: "{{ user_ansible['home'] }}"
    system: true

- name: Adds an SSH authorized key for user ansible
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ item }}"
  loop: "{{ user_ansible['keys'] }}"

- name: Configure passwordless sudo for user ansible
  ansible.builtin.copy:
    src: ansible-nopasswd
    dest: /etc/sudoers.d/
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -csf %s
