---
# tasks file for roles/ansible

- name: Install required packages
  ansible.builtin.apt:
    name:
      - sudo
      - openssh-server
      - python3-apt
    state: present
  tags:
    - sudo
    - ssh


- block:
    - name: Group ansible
      ansible.builtin.group:
        name: ansible
        system: true
        state: present

    - name: User ansible
      ansible.builtin.user:
        name: ansible
        group: ansible
        groups: sudo
        home: "{{ ansible_common.home }}"
        shell: /bin/sh
        system: true
        state: present
