---
# tasks file for roles/common

# Initial server configuration

- name: Include version-specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution_release }}.yml"
    hash_behaviour: merge
  tags: always


- name: apt configuration tasks
  when: "'raspberry' not in group_names"
  tags:
    - apt
    - sources-list
  block:
    - name: Remove default sources
      ansible.builtin.file:
        path: /etc/apt/sources.list
        state: absent

    - name: Use initial repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        update_cache: no
      loop: "{{ common_packages.repositories }}"

    - name: apt update
      ansible.builtin.apt:
        update_cache: yes


- name: Install packages
  ansible.builtin.apt:
    name: "{{ common_packages.install }}"
    state: present
  tags:
    - apt

- name: Install open-vm-tools
  ansible.builtin.apt:
    name: open-vm-tools
    state: latest
  when:
    - ansible_facts['virtualization_type'] == 'VMware'
    - ansible_facts['virtualization_role'] == 'guest'
  tags:
    - apt
    - vmware


# Network configuration
- name: Network configuration tasks
  tags: network
  block:
    - name: Setup hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '^\s*127\.0\.1\.1\b'
        line: "127.0.1.1\t{{ inventory_hostname }}\t{{ inventory_hostname_short }}"
        backup: yes

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"


- name: Make sure IPv6 is enabled
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '0'
  when: ansible_facts['virtualization_type'] not in ['lxc']
  tags:
    - sysctl
    - network

- name: Setup ntp time
  ansible.builtin.import_tasks: time.yml
  tags:
    - ntp
    - time

# - name: Nastaveni grub menu timeout
#   lineinfile:
#     dest: '/etc/default/grub'
#     regexp: 'GRUB_TIMEOUT'
#     line: 'GRUB_TIMEOUT=1'
#   notify: Update grub
#   when:
#     - ansible_facts['virtualization_type'] not in [ 'lxc' ]
#     - '"raspberry" not in group_names'

#   tags:
#     - grub
