---
# tasks file for roles/common

- name: Include version-specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution_release }}.yml"
    hash_behaviour: merge


- name: apt configuration tasks
  when: "'raspberry' not in group_names"
  tags:
    - apt
    - sources-list
  block:
    - name: Remove default sources
      ansible.builtin.file:
        path: /etc/apt/sources.list
        state: absent

    - name: Use initial repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        update_cache: no
      loop: "{{ common_packages.repositories }}"

    - name: apt update
      ansible.builtin.apt:
        update_cache: yes


- name: Install packages
  ansible.builtin.apt:
    name: "{{ common_packages.install }}"
    state: present
  tags:
    - apt

- name: Install open-vm-tools
  ansible.builtin.apt:
    name: open-vm-tools
    state: latest
  when:
    - ansible_facts['virtualization_type'] == 'VMware'
    - ansible_facts['virtualization_role'] == 'guest'
  tags:
    - apt
    - vmware
